// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mlwrqykozlznafwabexe.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1sd3JxeWtvemx6bmFmd2FiZXhlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDcxMTMzNzksImV4cCI6MjA2MjY4OTM3OX0.NYRuIUDgM9fIAE-sXNSt0i0kMOhxdstOlR5cC7yJAMA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);